services:
  etcd:
    image: bitnami/etcd
    environment:
      ETCD_ROOT_PASSWORD: "your_secure_password"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      - apisix-net
    volumes:
      - ./certs:/opt/bitnami/etcd/certs
      - etcd-data:/bitnami/etcd

  apisix-control:
    image: apache/apisix:latest
    environment:
      APISIX_LOCAL_CONF: "/usr/local/apisix/conf/config.yaml"
    ports:
      - "9180:9180"  # Admin API
    volumes:
      - ./apisix_controlPlane.yaml:/usr/local/apisix/conf/config.yaml
      - ./certs:/usr/local/apisix/certs
    networks:
      - apisix-net
    depends_on:
      - etcd

  apisix-data:
    image: apache/apisix:latest
    environment:
      APISIX_LOCAL_CONF: "/usr/local/apisix/conf/config.yaml"
    ports:
      - "9080:9080"  # HTTP
      - "9443:9443"  # HTTPS
    volumes:
      - ./apisix_dataPlane.yaml:/usr/local/apisix/conf/config.yaml
      - ./certs:/usr/local/apisix/certs
    networks:
      - apisix-net
    depends_on:
      - etcd

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    ports:
      - "9000:9000"
    volumes:
      - ./apisix_dashboard.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      - ./certs:/usr/local/apisix-dashboard/certs
    networks:
      - apisix-net
    depends_on:
      - etcd

  consul:
    image: bitnami/consul:latest
    networks:
      - apisix-net
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - 'consul_data:/bitnami'

  echo1:
    image: afrouper/echo-service:latest
    environment:
      echo_service_port: "8081"
      instance_name: "echo1"
    networks:
      - apisix-net

  echo2:
    image: afrouper/echo-service:latest
    environment:
      echo_service_port: "8082"
      instance_name: "echo2"
    networks:
      - apisix-net

  echo3:
    image: afrouper/echo-service:latest
    environment:
      echo_service_port: "8083"
      instance_name: "echo3"
    networks:
      - apisix-net

networks:
  apisix-net:
    driver: bridge

volumes:
  etcd-data:
  consul_data:
