#version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    networks:
      - kong-net
    volumes:
      - kong-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.8
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    networks:
      - kong-net
    depends_on:
      - kong-database

  kong-control-plane:
    image: kong:3.8
    container_name: kong-control-plane
    environment:
      KONG_ROLE: control_plane
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CLUSTER_LISTEN: '0.0.0.0:8005 ssl'
      KONG_CLUSTER_CERT: '/etc/kong/certs/kong-cluster.crt'
      KONG_CLUSTER_CERT_KEY: '/etc/kong/certs/kong-cluster.key'
      KONG_CLUSTER_CONTROL_PLANE: 'kong-control-plane:8005'
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
#      - "8000:8000"  # Proxy
#      - "8443:8443"  # Proxy SSL
      - "8005:8005"  # Cluster communication
      - "8001:8001"  # Admin API
      - "8444:8444"  # Admin API SSL
      - "8002:8002"  # Kong Manager UI
    volumes:
      - ./kong-cluster.crt:/etc/kong/certs/kong-cluster.crt
      - ./kong-cluster.key:/etc/kong/certs/kong-cluster.key
    networks:
      - kong-net
    depends_on:
      - kong-migrations

  kong-data-plane:
    image: kong:3.8
    container_name: kong-data-plane
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: off
      KONG_CLUSTER_CONTROL_PLANE: 'kong-control-plane:8005'
      KONG_CLUSTER_SERVER_NAME: 'kong_clustering'
      KONG_CLUSTER_CERT: '/etc/kong/certs/kong-cluster.crt'
      KONG_CLUSTER_CERT_KEY: '/etc/kong/certs/kong-cluster.key'
    ports:
      - "8000:8000"  # Proxy
      - "8443:8443"  # Proxy SSL
    volumes:
      - ./kong-cluster.crt:/etc/kong/certs/kong-cluster.crt
      - ./kong-cluster.key:/etc/kong/certs/kong-cluster.key
    networks:
      - kong-net
    depends_on:
      - kong-control-plane

#  konga:
#    image: pantsel/konga:latest
#    container_name: konga
#    environment:
#      DB_ADAPTER: postgres
#      DB_HOST: kong-database
#      DB_USER: kong
#      DB_PASSWORD: kongpass
#      DB_DATABASE: kong
#    ports:
#      - "1337:1337"  # Konga UI
#    networks:
#      - kong-net
#    depends_on:
#      - kong-control-plane
#      - kong-database

  echo1:
    image: afrouper/echo-service:latest
    container_name: echo1
    environment:
      echo_service_port: "8080"
      instance_name: "echo1"
    networks:
      - kong-net

  echo2:
    image: afrouper/echo-service:latest
    container_name: echo2
    environment:
      echo_service_port: "8081"
      instance_name: "echo2"
    networks:
      - kong-net

  echo3:
    image: afrouper/echo-service:latest
    container_name: echo3
    environment:
      echo_service_port: "8082"
      instance_name: "echo3"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  kong-data:
